services:
  # Database MongoDB
  mongodb:
    image: mongo:latest
    ports:
      - "27018:27017"
    volumes:
      - mongodb_data:/data/db

  # Backend API
  backend:
    build: ./backend
    ports:
      - "127.0.0.1:8001:8000"
    environment:
      - MONGO_URL=mongodb://mongodb:27017
      - DB_NAME=intranet_db
      - JWT_SECRET=gys-intranet-secret-key-2024
    depends_on:
      - mongodb

  # Frontend Web
  frontend:
    build: ./frontend
    ports:
      - "127.0.0.1:3001:3000"
    environment:
      # 1. Nama harus REACT_APP_BACKEND_URL
      # 2. Gunakan IP Server GYS (jangan localhost)
      # 3. JANGAN tambahkan /api di ujungnya
      - REACT_APP_BACKEND_URL=https://mygys.gyssteel.com:8000
      
      # --- TAMBAHKAN BARIS INI UNTUK FIX WEBSOCKET / BLANK PAGE ---
      - WDS_SOCKET_PORT=0 # Memaksa websocket mengikuti port URL web (443/HTTPS), bukan 3000
      - DANGEROUSLY_DISABLE_HOST_CHECK=true # Mencegah error 'Invalid Host Header' dari Nginx
      - FAST_REFRESH=false # (Opsional) Mematikan fitur auto-reload dev server yang sering crash di production
      # -----------------------------------------------------------
      
    depends_on:
      - backend
    stdin_open: true
    tty: true

volumes:
  mongodb_data:
    external: true
    name: gys-intranet_mongodb_data
